version: '3'
services:
  cscd488:
    container_name: cscd488
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  phpunit:
    container_name: phpunit
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: vendor/bin/phpunit
  bash:
    container_name: bash
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash