version: '3'
services:
  cscd488:
    container_name: cscd488
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  composer:
    image: composer:1.9.3
    environment:
      - COMPOSER_CHACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: never
  php:
    image: php:7.4-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
  phpunit:
    image: php:7.4-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
